# render.yaml
# This blueprint defines the services and database for the application.
# It uses the correct top-level keys for 'databases' and 'services'.

databases:
  # 1. The PostgreSQL Database
  # This section is dedicated to database definitions.
  - name: millionaire-maker-db
    databaseName: millionaire_maker_db
    user: mm_user
    plan: free

services:
  # 2. The Node.js Backend Server
  - type: web
    name: millionaire-maker-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: millionaire-maker-db
          property: connectionString

  # 3. The React Frontend (as a Web Service)
  - type: web
    name: millionaire-maker-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      # CORRECTED: We now directly set the value to the predictable public URL
      # of the backend service. Render creates URLs based on the service name.
      - key: REACT_APP_API_URL
        value: https://millionaire-maker-backend.onrender.com
