# render.yaml
# This is the blueprint for deploying the Millionaire Maker application on Render.
# It defines three services: a PostgreSQL database, a Node.js backend, and a React frontend.

services:
  # 1. The PostgreSQL Database
  # The 'pserv' type is for Render's managed PostgreSQL instances.
  - type: pserv
    name: millionaire-maker-db
    # Specifying the free plan is good practice.
    plan: free
    # These values will be used to create the database and user.
    databaseName: millionaire_maker_db
    user: mm_user

  # 2. The Node.js Backend Server
  # We define this as a 'web' service with a 'docker' runtime.
  - type: web
    name: millionaire-maker-backend
    runtime: docker # CRITICAL FIX: Explicitly tells Render to use the Dockerfile.
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: millionaire-maker-db
          property: connectionString # This correctly links the database to the backend.

  # 3. The React Frontend (as a Web Service)
  # This is also a 'web' service using Docker.
  - type: web
    name: millionaire-maker-frontend
    runtime: docker # CRITICAL FIX: Explicitly tells Render to use the Dockerfile.
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: millionaire-maker-backend
          property: url # This correctly links the frontend to the backend's public URL.
