# render.yaml
# This blueprint defines the services and database for the application.
# It uses the correct top-level keys for 'databases' and 'services'.

databases:
  # 1. The PostgreSQL Database
  # This section is dedicated to database definitions.
  - name: millionaire-maker-db
    # Render will create a database with this name inside the instance.
    databaseName: millionaire_maker_db
    # Render will create a user with this name.
    user: mm_user
    plan: free

services:
  # 2. The Node.js Backend Server
  - type: web
    name: millionaire-maker-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          # This correctly references the database defined above.
          name: millionaire-maker-db
          property: connectionString

  # 3. The React Frontend (as a Web Service)
  - type: web
    name: millionaire-maker-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          # CORRECTED: Added the required 'type' field.
          type: web
          # This now correctly references the backend web service.
          name: millionaire-maker-backend
          property: url
