# render.yaml
# This is the blueprint for deploying the Millionaire Maker application on Render.
# It defines three services: a PostgreSQL database, a Node.js backend, and a React frontend.

services:
  # 1. The PostgreSQL Database
  - type: pserv
    name: millionaire-maker-db
    ipAllowList: [] # Allows all IPs to connect. For production, you might restrict this.

  # 2. The Node.js Backend Server
  - type: web
    name: millionaire-maker-backend
    # The build context is the repo root.
    # The dockerfilePath is relative to the repo root.
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: millionaire-maker-db
          property: connectionString

  # 3. The React Frontend (as a Web Service)
  - type: web
    name: millionaire-maker-frontend
    # The build context is the repo root.
    # The dockerfilePath is relative to the repo root.
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: millionaire-maker-backend
          property: url
