services:
  # 1. The PostgreSQL Database
  - type: pserv
    name: millionaire-maker-db
    plan: free
    databaseName: millionaire_maker_db
    user: mm_user

  # 2. The Node.js Backend Server
  - type: web
    name: millionaire-maker-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: millionaire-maker-db
          property: connectionString

  # 3. The React Frontend (as a Web Service)
  - type: web
    name: millionaire-maker-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: millionaire-maker-backend
          property: url
